[package]
name = "prog-vb"
version = "0.11.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

[dependencies]
hidapi = "1.0.1"
argparse = "0.2.2"
indicatif = "0.12.0"
calm_io = "0.1.1"
eyre = "0.3"
