[package]
name = "prog-vb"
version = "0.10.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

[dependencies]
hidapi = "0.5.0"
argparse = "0.2.2"
failure = "0.1.5"
exitfailure = "0.5.1"
indicatif = "0.11.0"
